name: Angular Deploy to GitHub Pages

on:
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm ci

    - name: Install Angular CLI
      run: npm install -g @angular/cli

    - name: Check Angular CLI version
      run: ng version

    - name: Replace environment variables
      run: |
        sed -i 's|AIRTABLE_URL_PLACEHOLDER|'"${{ secrets.APIURL }}"'|g' src/environments/environment.prod.ts
        sed -i 's|AIRTABLE_API_KEY_PLACEHOLDER|'"${{ secrets.APIKEY }}"'|g' src/environments/environment.prod.ts
        sed -i 's|BREVO_API_KEY_PLACEHOLDER|'"${{ secrets.APIKEYBREVO }}"'|g' src/environments/environment.prod.ts
    
    - name: Build production app
      run: ng build --configuration production --base-href="/AlterEgoAdventures/"

    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@4.1.0
      with:
        branch: gh-pages
        folder: dist/alter-ego-adventures/browser
